core:
  base_price: 1.0
  # Not: overlap_pct ve num_orders burada default; asıl aralıklar CLI ile taranacak
  overlap_pct: 10.0
  num_orders: 10
  seed:

generation:
  wave_pattern: true
  wave_mode: anchors
  anchors: 9
  blocks: 3
  wave_amp_min: 0.05
  wave_amp_max: 0.30
  wave_strong_threshold: 50.0
  wave_weak_threshold: 10.0
  use_smart_init: false
  history_db:
  min_indent_step: 0.05
  softmax_temp: 1.4
  first_volume_target: 0.01     # toplam hacmin %1'i ile başla
  first_indent_target: 0.00

constraints:
  m2_min: 0.10
  m2_max: 1.00
  m_min: 0.05
  m_max: 1.00
  g_min: 1.01
  g_max: 1.20
  slope_cap: 0.25
  strict_inc_eps: 0.000001
  second_upper_c2: 2.0
  q1_cap: 22.0
  tail_floor: 32.0
  tail_cap: 0.40
  m_head: 0.40
  m_tail: 0.20
  tau_scale: 0.3333333333333333
  use_hc0_bootstrap: true
  use_head_budget: false        # geniş taramada serbest bırakıyoruz; istersen true + head_budget_pct: 0.35 yap
  head_budget_pct: 2.0
  firstK_min: 1.0
  k_front: 3
  front_cap: 5.0

penalties:
  # geniş arama için biraz yumuşak tutuyoruz; wave açık olduğu için w_wave/w_wave_shape var
  w_fixed: 2.0
  w_second: 2.0
  w_band: 1.5
  w_front: 2.0
  w_tv: 3.5
  w_wave: 0.75
  w_varm: 2.0
  w_blocks: 1.0
  w_plateau: 2.0
  w_front_share: 2.0
  w_tailweak: 2.0
  w_slope: 1.0
  w_wave_shape: 1.2
  # New penalties
  w_sens: 1.0
  sens_min: 0.25
  w_template: 0.8
  template_close: 0.6
  penalty_preset:
  target_std: 0.10

scoring:
  alpha: 0.50
  beta: 0.30
  gamma: 0.25     # tail’e makul ağırlık
  lambda_penalty: 0.08

adaptive:
  use_adaptive: false
  strategy_type: balanced

normalization:
  post_round_2dp: false
  post_round_strategy: tail-first
  post_round_m2_tolerance: 0.05
  post_round_keep_v1_band: true